import type { PracticeDifficulty, PracticeSubject } from "@/lib/types/student";

type SeedQuestion = {
  subject: PracticeSubject;
  difficulty: PracticeDifficulty;
  subtopic: string;
  prompt: string;
  choice_a: string;
  choice_b: string;
  choice_c: string;
  choice_d: string;
  correct_choice: "A" | "B" | "C" | "D";
  explanation: string;
};

export const QUESTION_BANK: SeedQuestion[] = [
  {
    subject: "math",
    difficulty: "easy",
    subtopic: "Linear equations",
    prompt: "If 4x + 3 = 19, what is the value of x?",
    choice_a: "3",
    choice_b: "4",
    choice_c: "5",
    choice_d: "6",
    correct_choice: "B",
    explanation: "Subtract 3 from both sides to get 4x = 16, then divide by 4."
  },
  {
    subject: "math",
    difficulty: "easy",
    subtopic: "Linear equations",
    prompt: "What is the solution to 7y - 14 = 21?",
    choice_a: "3",
    choice_b: "4",
    choice_c: "5",
    choice_d: "7",
    correct_choice: "C",
    explanation: "Add 14 to both sides to get 7y = 35, then divide by 7."
  },
  {
    subject: "math",
    difficulty: "easy",
    subtopic: "Percentages",
    prompt: "A jacket that costs $80 is on sale for 25% off. What is the sale price?",
    choice_a: "$55",
    choice_b: "$60",
    choice_c: "$65",
    choice_d: "$70",
    correct_choice: "B",
    explanation: "Twenty-five percent of 80 is 20, so the sale price is 80 - 20."
  },
  {
    subject: "math",
    difficulty: "easy",
    subtopic: "Ratios and proportions",
    prompt: "If 3 notebooks cost $9, how much would 5 notebooks cost at the same rate?",
    choice_a: "$12",
    choice_b: "$15",
    choice_c: "$18",
    choice_d: "$20",
    correct_choice: "B",
    explanation: "Each notebook costs $3, so 5 notebooks cost 5 x 3."
  },
  {
    subject: "math",
    difficulty: "easy",
    subtopic: "Area",
    prompt: "A rectangle has length 8 and width 5. What is its area?",
    choice_a: "13",
    choice_b: "26",
    choice_c: "40",
    choice_d: "80",
    correct_choice: "C",
    explanation: "Area of a rectangle is length times width."
  },
  {
    subject: "math",
    difficulty: "easy",
    subtopic: "Mean",
    prompt: "What is the mean of 6, 8, 10, and 12?",
    choice_a: "8",
    choice_b: "9",
    choice_c: "10",
    choice_d: "11",
    correct_choice: "B",
    explanation: "Add the numbers to get 36, then divide by 4."
  },
  {
    subject: "math",
    difficulty: "medium",
    subtopic: "Heart of Algebra",
    prompt: "The system of equations 2x + y = 13 and x - y = 2 is solved by the ordered pair (x, y). What is the value of x?",
    choice_a: "3",
    choice_b: "5",
    choice_c: "7",
    choice_d: "9",
    correct_choice: "B",
    explanation: "Substitute y = x - 2 into 2x + y = 13, giving 3x - 2 = 13 and x = 5."
  },
  {
    subject: "math",
    difficulty: "medium",
    subtopic: "Systems of equations",
    prompt: "If x + y = 11 and x - y = 3, what is the value of x?",
    choice_a: "4",
    choice_b: "6",
    choice_c: "7",
    choice_d: "8",
    correct_choice: "C",
    explanation: "Add the equations to get 2x = 14, then divide by 2."
  },
  {
    subject: "math",
    difficulty: "medium",
    subtopic: "Functions",
    prompt: "If f(x) = 3x - 4, what is f(6)?",
    choice_a: "10",
    choice_b: "12",
    choice_c: "14",
    choice_d: "18",
    correct_choice: "C",
    explanation: "Substitute 6 for x: 3(6) - 4 = 18 - 4 = 14."
  },
  {
    subject: "math",
    difficulty: "medium",
    subtopic: "Quadratics",
    prompt: "Which value of x is a solution to x^2 - 9 = 0?",
    choice_a: "1",
    choice_b: "3",
    choice_c: "6",
    choice_d: "9",
    correct_choice: "B",
    explanation: "Solve x^2 = 9. The solutions are 3 and -3, so 3 is a correct choice."
  },
  {
    subject: "math",
    difficulty: "medium",
    subtopic: "Data analysis",
    prompt: "A student scores 72, 78, and 90 on three quizzes. What score is needed on a fourth quiz to have an average of 80?",
    choice_a: "76",
    choice_b: "78",
    choice_c: "80",
    choice_d: "84",
    correct_choice: "C",
    explanation: "An average of 80 on 4 quizzes requires a total of 320 points. The first 3 total 240."
  },
  {
    subject: "math",
    difficulty: "medium",
    subtopic: "Exponents",
    prompt: "What is the value of 2^3 x 2^2?",
    choice_a: "16",
    choice_b: "24",
    choice_c: "32",
    choice_d: "64",
    correct_choice: "C",
    explanation: "Add exponents with the same base: 2^(3+2) = 2^5 = 32."
  },
  {
    subject: "math",
    difficulty: "medium",
    subtopic: "Slope",
    prompt: "What is the slope of the line passing through (2, 3) and (6, 11)?",
    choice_a: "1",
    choice_b: "2",
    choice_c: "3",
    choice_d: "4",
    correct_choice: "B",
    explanation: "Slope is rise over run: (11 - 3) / (6 - 2) = 8 / 4 = 2."
  },
  {
    subject: "math",
    difficulty: "hard",
    subtopic: "Quadratics",
    prompt: "If x^2 - 5x + 6 = 0, what is the sum of the solutions?",
    choice_a: "5",
    choice_b: "6",
    choice_c: "11",
    choice_d: "30",
    correct_choice: "A",
    explanation: "For ax^2 + bx + c = 0, the sum of the roots is -b/a. Here that is 5."
  },
  {
    subject: "math",
    difficulty: "hard",
    subtopic: "Nonlinear functions",
    prompt: "If g(x) = (x - 1)(x + 4), what is g(3)?",
    choice_a: "10",
    choice_b: "12",
    choice_c: "14",
    choice_d: "16",
    correct_choice: "C",
    explanation: "Substitute x = 3: (3 - 1)(3 + 4) = 2 x 7 = 14."
  },
  {
    subject: "math",
    difficulty: "hard",
    subtopic: "Radicals",
    prompt: "If sqrt(3x + 1) = 5, what is the value of x?",
    choice_a: "6",
    choice_b: "7",
    choice_c: "8",
    choice_d: "9",
    correct_choice: "C",
    explanation: "Square both sides to get 3x + 1 = 25, then solve 3x = 24."
  },
  {
    subject: "math",
    difficulty: "hard",
    subtopic: "Systems of equations",
    prompt: "The system y = 2x + 1 and y = -x + 10 intersects at what value of x?",
    choice_a: "2",
    choice_b: "3",
    choice_c: "4",
    choice_d: "5",
    correct_choice: "B",
    explanation: "Set the expressions for y equal: 2x + 1 = -x + 10, so 3x = 9."
  },
  {
    subject: "math",
    difficulty: "hard",
    subtopic: "Probability",
    prompt: "A bag contains 4 red marbles and 6 blue marbles. What is the probability of drawing a red marble?",
    choice_a: "1/5",
    choice_b: "2/5",
    choice_c: "3/5",
    choice_d: "4/5",
    correct_choice: "B",
    explanation: "There are 10 marbles total, and 4 of them are red, so the probability is 4/10."
  },
  {
    subject: "math",
    difficulty: "hard",
    subtopic: "Percentages",
    prompt: "A quantity increases from 50 to 65. What is the percent increase?",
    choice_a: "15%",
    choice_b: "20%",
    choice_c: "30%",
    choice_d: "35%",
    correct_choice: "C",
    explanation: "The increase is 15, and 15/50 = 0.3, or 30%."
  },
  {
    subject: "math",
    difficulty: "hard",
    subtopic: "Geometry",
    prompt: "The circumference of a circle is 10pi. What is the radius?",
    choice_a: "5",
    choice_b: "10",
    choice_c: "20",
    choice_d: "25",
    correct_choice: "A",
    explanation: "Use C = 2pi r. If 10pi = 2pi r, then r = 5."
  },
  {
    subject: "math",
    difficulty: "hard",
    subtopic: "Linear inequalities",
    prompt: "Which value satisfies 3x - 4 > 11?",
    choice_a: "4",
    choice_b: "5",
    choice_c: "6",
    choice_d: "7",
    correct_choice: "C",
    explanation: "Solve 3x > 15, so x > 5. A value like 6 satisfies the inequality."
  },
  {
    subject: "reading-writing",
    difficulty: "easy",
    subtopic: "Transitions",
    prompt: "The experiment yielded promising early data. ______, the researchers decided to continue the trial for another month.",
    choice_a: "However,",
    choice_b: "Therefore,",
    choice_c: "Instead,",
    choice_d: "Likewise,",
    correct_choice: "B",
    explanation: "The second sentence is a result of the first, so a cause-and-effect transition fits."
  },
  {
    subject: "reading-writing",
    difficulty: "easy",
    subtopic: "Sentence boundaries",
    prompt: "Which choice completes the text so that it is grammatically standard English? Maya loves astronomy ______ she visits the planetarium every month.",
    choice_a: ", and",
    choice_b: " and",
    choice_c: "; and",
    choice_d: ". and",
    correct_choice: "A",
    explanation: "Two independent clauses can be joined with a comma and a coordinating conjunction."
  },
  {
    subject: "reading-writing",
    difficulty: "easy",
    subtopic: "Word choice",
    prompt: "The museum's new exhibit was so ______ that visitors stayed for hours.",
    choice_a: "engaging",
    choice_b: "engagement",
    choice_c: "engage",
    choice_d: "engagedly",
    correct_choice: "A",
    explanation: "The sentence needs an adjective to describe the exhibit."
  },
  {
    subject: "reading-writing",
    difficulty: "easy",
    subtopic: "Punctuation",
    prompt: "Lena packed three essentials for the hike ______ water, sunscreen, and a map.",
    choice_a: ":",
    choice_b: ",",
    choice_c: ";",
    choice_d: "-",
    correct_choice: "A",
    explanation: "A colon correctly introduces the list after an independent clause."
  },
  {
    subject: "reading-writing",
    difficulty: "easy",
    subtopic: "Rhetorical synthesis",
    prompt: "A student wants to emphasize that bees help crops grow. Which choice best uses that idea? Bees pollinate flowering plants. Many crops depend on pollination to produce fruit.",
    choice_a: "Bees are insects with striped bodies.",
    choice_b: "Bees help many crops produce fruit by pollinating flowering plants.",
    choice_c: "Some farms grow fruit, and bees live outdoors.",
    choice_d: "Pollination happens in nature all the time.",
    correct_choice: "B",
    explanation: "That choice directly combines both notes into a clear claim about crops."
  },
  {
    subject: "reading-writing",
    difficulty: "easy",
    subtopic: "Central ideas",
    prompt: "A passage explains how public libraries offer internet access, tutoring, and job-search support. Which choice best states the passage's central idea?",
    choice_a: "Libraries mainly store old books.",
    choice_b: "Libraries are quieter than most schools.",
    choice_c: "Libraries provide several services that support communities.",
    choice_d: "Libraries should always stay open late.",
    correct_choice: "C",
    explanation: "That option captures the shared idea across all the supporting details."
  },
  {
    subject: "reading-writing",
    difficulty: "medium",
    subtopic: "Command of evidence",
    prompt: "A passage claims that urban trees can reduce summer temperatures. Which finding would best support that claim?",
    choice_a: "Cities plant trees in the spring.",
    choice_b: "Neighborhoods with more tree cover are often several degrees cooler than nearby areas with less shade.",
    choice_c: "Some trees lose leaves in the fall.",
    choice_d: "Many people enjoy visiting parks on weekends.",
    correct_choice: "B",
    explanation: "This finding directly supports the claim by showing a measurable cooling effect."
  },
  {
    subject: "reading-writing",
    difficulty: "medium",
    subtopic: "Transitions",
    prompt: "Kai's first design draft solved the storage problem. ______, it left little room for natural light, so the team revised it.",
    choice_a: "For example,",
    choice_b: "Meanwhile,",
    choice_c: "Still,",
    choice_d: "Similarly,",
    correct_choice: "C",
    explanation: "The second clause introduces a contrast to the first idea."
  },
  {
    subject: "reading-writing",
    difficulty: "medium",
    subtopic: "Verb forms",
    prompt: "By the time the lecture began, the students ______ their notes and opened the assigned article.",
    choice_a: "organize",
    choice_b: "had organized",
    choice_c: "will organize",
    choice_d: "are organizing",
    correct_choice: "B",
    explanation: "Past perfect shows an action completed before another past action."
  },
  {
    subject: "reading-writing",
    difficulty: "medium",
    subtopic: "Sentence boundaries",
    prompt: "The chef tested the recipe several times ______ she wanted the texture to be consistent.",
    choice_a: "because",
    choice_b: "however",
    choice_c: "for example",
    choice_d: "meanwhile",
    correct_choice: "A",
    explanation: "The second clause explains the reason for the first."
  },
  {
    subject: "reading-writing",
    difficulty: "medium",
    subtopic: "Inferences",
    prompt: "A passage notes that a cyclist left before sunrise, packed extra water, and avoided the busiest roads. What can reasonably be inferred?",
    choice_a: "The cyclist preferred a quiet, longer ride.",
    choice_b: "The cyclist forgot a map.",
    choice_c: "The cyclist was training for a race that day.",
    choice_d: "The cyclist disliked mornings.",
    correct_choice: "A",
    explanation: "The details suggest planning for a calm ride with fewer people and warmer hours."
  },
  {
    subject: "reading-writing",
    difficulty: "medium",
    subtopic: "Text structure",
    prompt: "A paragraph introduces a problem, explains several attempted solutions, and ends by describing the most effective one. Which structure best describes the paragraph?",
    choice_a: "Cause and effect",
    choice_b: "Problem and solution",
    choice_c: "Chronological narrative",
    choice_d: "Comparison and contrast",
    correct_choice: "B",
    explanation: "The paragraph centers on a problem and the solution that worked best."
  },
  {
    subject: "reading-writing",
    difficulty: "medium",
    subtopic: "Punctuation",
    prompt: "The novelist revised the final chapter twice ______ first to clarify the timeline and then to sharpen the ending.",
    choice_a: ",",
    choice_b: ";",
    choice_c: ":",
    choice_d: "-",
    correct_choice: "C",
    explanation: "A colon neatly introduces the explanation that follows the complete clause."
  },
  {
    subject: "reading-writing",
    difficulty: "hard",
    subtopic: "Rhetorical synthesis",
    prompt: "Notes: 1. The app tracks how long users study. 2. Students can compare weekly totals. 3. Teachers use the totals to plan review sessions. Which choice best combines the notes?",
    choice_a: "The app tracks study time, lets students compare weekly totals, and gives teachers data for planning review sessions.",
    choice_b: "Teachers like to plan sessions, and students study in many different ways.",
    choice_c: "The app is digital, and totals are usually measured weekly.",
    choice_d: "Students compare totals because teachers like data.",
    correct_choice: "A",
    explanation: "That choice accurately integrates all three notes into one clear sentence."
  },
  {
    subject: "reading-writing",
    difficulty: "hard",
    subtopic: "Command of evidence",
    prompt: "A writer argues that community gardens strengthen neighborhoods. Which quotation would best support that claim?",
    choice_a: "\"Tomatoes can be difficult to grow in colder climates.\"",
    choice_b: "\"Many gardeners said the shared plot helped them meet neighbors they had never spoken with before.\"",
    choice_c: "\"Community gardens often require compost and mulch.\"",
    choice_d: "\"The garden opened on a Saturday in early May.\"",
    correct_choice: "B",
    explanation: "The quotation directly shows how the garden built stronger social connections."
  },
  {
    subject: "reading-writing",
    difficulty: "hard",
    subtopic: "Transitions",
    prompt: "The original bridge design was affordable. ______, engineers rejected it because it could not support the required weight.",
    choice_a: "As a result,",
    choice_b: "Likewise,",
    choice_c: "Nevertheless,",
    choice_d: "For instance,",
    correct_choice: "C",
    explanation: "The second clause contrasts with the first, so a concession transition is needed."
  },
  {
    subject: "reading-writing",
    difficulty: "hard",
    subtopic: "Sentence placement",
    prompt: "A paragraph discusses a scientist's early experiments, a later breakthrough, and her influence on future researchers. Where would the sentence 'That breakthrough transformed the field's understanding of cell repair' best fit?",
    choice_a: "Before the early experiments are mentioned",
    choice_b: "Immediately after the later breakthrough is described",
    choice_c: "At the very start of the paragraph",
    choice_d: "After the influence on future researchers is discussed",
    correct_choice: "B",
    explanation: "The sentence refers back to the breakthrough, so it belongs right after that idea."
  },
  {
    subject: "reading-writing",
    difficulty: "hard",
    subtopic: "Precision",
    prompt: "The reviewer praised the documentary for its ______ use of archival footage, noting that every clip advanced the film's central argument.",
    choice_a: "random",
    choice_b: "strategic",
    choice_c: "ordinary",
    choice_d: "silent",
    correct_choice: "B",
    explanation: "Strategic best matches the idea that each clip served a clear purpose."
  },
  {
    subject: "reading-writing",
    difficulty: "hard",
    subtopic: "Inferences",
    prompt: "A biographer writes that the inventor kept careful notebooks, revised designs repeatedly, and tested small changes before making larger ones. What does this most strongly suggest?",
    choice_a: "The inventor preferred publicity to precision.",
    choice_b: "The inventor worked in isolation.",
    choice_c: "The inventor approached problems methodically.",
    choice_d: "The inventor rarely finished projects.",
    correct_choice: "C",
    explanation: "The details point to a careful, systematic process."
  },
  {
    subject: "reading-writing",
    difficulty: "hard",
    subtopic: "Text structure",
    prompt: "A passage opens with a common misconception, then explains why research does not support it, and finally offers a more accurate explanation. Which structure best describes the passage?",
    choice_a: "Claim, counterclaim, resolution",
    choice_b: "Chronological account",
    choice_c: "Description of a process",
    choice_d: "Personal reflection",
    correct_choice: "A",
    explanation: "The passage introduces an idea, challenges it, then replaces it with a better explanation."
  },
  {
    subject: "reading-writing",
    difficulty: "hard",
    subtopic: "Form, structure, and sense",
    prompt: "The committee members, along with the chair, ______ planning a revised schedule for the event.",
    choice_a: "is",
    choice_b: "was",
    choice_c: "are",
    choice_d: "has been",
    correct_choice: "C",
    explanation: "The subject is members, which is plural, so the verb should be are."
  }
];
